// <auto-generated />
using System;
using Buzz.Jewelcrafting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buzz.Jewelcrafting.Migrations
{
    [DbContext(typeof(BuzzDbContext))]
    [Migration("20220929215246_Change_User_Id")]
    partial class Change_User_Id
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.BuzzUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("GemCutId")
                        .HasColumnType("integer");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("JewelryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GemCutId");

                    b.HasIndex("JewelryId");

                    b.ToTable("Designs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 6,
                            ItemId = 42649,
                            JewelryId = 1,
                            Name = "Design: Titanium Earthguard Ring",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 6,
                            ItemId = 42650,
                            JewelryId = 2,
                            Name = "Design: Titanium Spellshock Ring",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 6,
                            ItemId = 43597,
                            JewelryId = 3,
                            Name = "Design: Titanium Frostguard Ring",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 6,
                            ItemId = 42648,
                            JewelryId = 4,
                            Name = "Design: Titanium Impact Band",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 6,
                            ItemId = 42651,
                            JewelryId = 5,
                            Name = "Design: Titanium Impact Choker",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 6,
                            ItemId = 42653,
                            JewelryId = 6,
                            Name = "Design: Titanium Spellshock Necklace",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 6,
                            ItemId = 42652,
                            JewelryId = 7,
                            Name = "Design: Titanium Earthguard Chain",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 5,
                            GemCutId = 1,
                            ItemId = 41710,
                            Name = "Design: Relentless Earthsiege Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 5,
                            GemCutId = 2,
                            ItemId = 41704,
                            Name = "Design: Chaotic Skyflare Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 5,
                            GemCutId = 3,
                            ItemId = 41708,
                            Name = "Design: Insightful Earthsiege Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 5,
                            GemCutId = 4,
                            ItemId = 41706,
                            Name = "Design: Ember Skyflare Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 5,
                            GemCutId = 5,
                            ItemId = 41709,
                            Name = "Design: Invigorating Earthsiege Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 5,
                            GemCutId = 6,
                            ItemId = 41707,
                            Name = "Design: Revitalizing Skyflare Diamond",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 3,
                            GemCutId = 7,
                            ItemId = 41576,
                            Name = "Design: Bold Scarlet Ruby",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 3,
                            GemCutId = 8,
                            ItemId = 42138,
                            Name = "Design: Solid Sky Sapphire",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 3,
                            GemCutId = 9,
                            ItemId = 41577,
                            Name = "Design: Delicate Scarlet Ruby",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 3,
                            GemCutId = 10,
                            ItemId = 41697,
                            Name = "Design: Enduring Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 3,
                            GemCutId = 11,
                            ItemId = 41690,
                            Name = "Design: Reckless Monarch Topaz",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 3,
                            GemCutId = 12,
                            ItemId = 41580,
                            Name = "Design: Rigid Autumn's Glow",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 3,
                            GemCutId = 13,
                            ItemId = 41688,
                            Name = "Design: Veiled Monarch Topaz",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 3,
                            GemCutId = 14,
                            ItemId = 41579,
                            Name = "Design: Quick Autumn's Glow",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 3,
                            GemCutId = 15,
                            ItemId = 41699,
                            Name = "Design: Seer's Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 3,
                            GemCutId = 16,
                            ItemId = 41582,
                            Name = "Design: Glinting Monarch Topaz",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 3,
                            GemCutId = 17,
                            ItemId = 41689,
                            Name = "Design: Luminous Monarch Topaz",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 3,
                            GemCutId = 18,
                            ItemId = 41719,
                            Name = "Design: Subtle Scarlet Ruby",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 26,
                            Cost = 3,
                            GemCutId = 19,
                            ItemId = 41703,
                            Name = "Design: Regal Twilight Opal",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 27,
                            Cost = 3,
                            GemCutId = 20,
                            ItemId = 41701,
                            Name = "Design: Royal Twilight Opal",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 28,
                            Cost = 3,
                            GemCutId = 21,
                            ItemId = 41694,
                            Name = "Design: Intricate Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 29,
                            Cost = 3,
                            GemCutId = 22,
                            ItemId = 41692,
                            Name = "Design: Energized Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 30,
                            Cost = 3,
                            GemCutId = 23,
                            ItemId = 41581,
                            Name = "Design: Lustrous Sky Sapphire",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 31,
                            Cost = 3,
                            GemCutId = 24,
                            ItemId = 41698,
                            Name = "Design: Vivid Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 32,
                            Cost = 3,
                            GemCutId = 25,
                            ItemId = 41578,
                            Name = "Design: Flashing Scarlet Ruby",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 33,
                            Cost = 3,
                            GemCutId = 26,
                            ItemId = 41696,
                            Name = "Design: Lambent Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 34,
                            Cost = 3,
                            GemCutId = 27,
                            ItemId = 41747,
                            Name = "Design: Shifting Twilight Opal",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 35,
                            Cost = 3,
                            GemCutId = 28,
                            ItemId = 41693,
                            Name = "Design: Forceful Forest Emerald",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 36,
                            Cost = 3,
                            GemCutId = 29,
                            ItemId = 41686,
                            Name = "Design: Potent Monarch Topaz",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 37,
                            Cost = 3,
                            GemCutId = 30,
                            ItemId = 41702,
                            Name = "Design: Puissant Twilight Opal",
                            Source = "Token"
                        },
                        new
                        {
                            Id = 38,
                            Cost = 3,
                            GemCutId = 31,
                            ItemId = 41687,
                            Name = "Design: Stark Monarch Topaz",
                            Source = "Token"
                        });
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.GemCut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Stat1")
                        .HasColumnType("text");

                    b.Property<string>("Stat2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GemCuts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_shadowspirit_02",
                            ItemId = 41398,
                            Name = "Relentless Earthsiege Diamond"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_icediamond_02",
                            ItemId = 41258,
                            Name = "Chaotic Skyflare Diamond"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_shadowspirit_02",
                            ItemId = 41401,
                            Name = "Insightful Earthsiege Diamond"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_icediamond_02",
                            ItemId = 41333,
                            Name = "Ember Skyflare Diamond"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_shadowspirit_02",
                            ItemId = 41385,
                            Name = "Invigorating Earthsiege Diamond"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Meta",
                            IconName = "inv_jewelcrafting_icediamond_02",
                            ItemId = 41376,
                            Name = "Revitalizing Skyflare Diamond"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Red",
                            IconName = "inv_jewelcrafting_gem_28",
                            ItemId = 39996,
                            Name = "Bold Scarlet Ruby",
                            Stat1 = "Strength"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Blue",
                            IconName = "inv_jewelcrafting_gem_27",
                            ItemId = 40008,
                            Name = "Solid Sky Sapphire",
                            Stat1 = "Stamina"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Red",
                            IconName = "inv_jewelcrafting_gem_28",
                            ItemId = 39997,
                            Name = "Delicate Scarlet Ruby",
                            Stat1 = "Agility"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40089,
                            Name = "Enduring Forest Emerald",
                            Stat1 = "Defense Rating",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40051,
                            Name = "Reckless Monarch Topaz",
                            Stat1 = "Spell Power",
                            Stat2 = "Haste"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Yellow",
                            IconName = "inv_jewelcrafting_gem_26",
                            ItemId = 40014,
                            Name = "Rigid Autumn's Glow",
                            Stat1 = "Hit Rating"
                        },
                        new
                        {
                            Id = 13,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40049,
                            Name = "Veiled Monarch Topaz",
                            Stat1 = "Spell Power",
                            Stat2 = "Hit Rating"
                        },
                        new
                        {
                            Id = 14,
                            Color = "Yellow",
                            IconName = "inv_jewelcrafting_gem_26",
                            ItemId = 40017,
                            Name = "Quick Autumn's Glow",
                            Stat1 = "Haste Rating"
                        },
                        new
                        {
                            Id = 15,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40092,
                            Name = "Seer's Forest Emerald",
                            Stat1 = "Intellect",
                            Stat2 = "Spirit"
                        },
                        new
                        {
                            Id = 16,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40044,
                            Name = "Glinting Monarch Topaz",
                            Stat1 = "Agility",
                            Stat2 = "Hit Rating"
                        },
                        new
                        {
                            Id = 17,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40047,
                            Name = "Luminous Monarch Topaz",
                            Stat1 = "Luminous",
                            Stat2 = "Intellect"
                        },
                        new
                        {
                            Id = 18,
                            Color = "Red",
                            IconName = "inv_jewelcrafting_gem_28",
                            ItemId = 40000,
                            Name = "Subtle Scarlet Ruby",
                            Stat1 = "Dodge Rating"
                        },
                        new
                        {
                            Id = 19,
                            Color = "Purple",
                            IconName = "inv_jewelcrafting_gem_29",
                            ItemId = 40031,
                            Name = "Regal Twilight Opal",
                            Stat1 = "Dodge Rating",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 20,
                            Color = "Purple",
                            IconName = "inv_jewelcrafting_gem_29",
                            ItemId = 40027,
                            Name = "Royal Twilight Opal",
                            Stat1 = "Spell Power",
                            Stat2 = "Mp5"
                        },
                        new
                        {
                            Id = 21,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40104,
                            Name = "Intricate Forest Emerald",
                            Stat1 = "Haste Rating",
                            Stat2 = "Spirit"
                        },
                        new
                        {
                            Id = 22,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40105,
                            Name = "Energized Forest Emerald",
                            Stat1 = "Haste Rating",
                            Stat2 = "Mp5"
                        },
                        new
                        {
                            Id = 23,
                            Color = "Blue",
                            IconName = "inv_jewelcrafting_gem_27",
                            ItemId = 40010,
                            Name = "Lustrous Sky Sapphire",
                            Stat1 = "Mp5"
                        },
                        new
                        {
                            Id = 24,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40088,
                            Name = "Vivid Forest Emerald",
                            Stat1 = "Hit Rating",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 25,
                            Color = "Red",
                            IconName = "inv_jewelcrafting_gem_28",
                            ItemId = 40001,
                            Name = "Flashing Scarlet Ruby",
                            Stat1 = "Parry Rating"
                        },
                        new
                        {
                            Id = 26,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40100,
                            Name = "Lambent Forest Emerald",
                            Stat1 = "Hit Rating",
                            Stat2 = "Mp5"
                        },
                        new
                        {
                            Id = 27,
                            Color = "Purple",
                            IconName = "inv_jewelcrafting_gem_29",
                            ItemId = 40023,
                            Name = "Shifting Twilight Opal",
                            Stat1 = "Agility",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 28,
                            Color = "Green",
                            IconName = "inv_jewelcrafting_gem_25",
                            ItemId = 40091,
                            Name = "Forceful Forest Emerald",
                            Stat1 = "Haste Rating",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 29,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40048,
                            Name = "Potent Monarch Topaz",
                            Stat1 = "Spell Power",
                            Stat2 = "Critical Strike Rating"
                        },
                        new
                        {
                            Id = 30,
                            Color = "Purple",
                            IconName = "inv_jewelcrafting_gem_29",
                            ItemId = 40033,
                            Name = "Puissant Twilight Opal",
                            Stat1 = "Armor Penetration Rating",
                            Stat2 = "Stamina"
                        },
                        new
                        {
                            Id = 31,
                            Color = "Orange",
                            IconName = "inv_jewelcrafting_gem_30",
                            ItemId = 40055,
                            Name = "Stark Monarch Topaz",
                            Stat1 = "Attack Power",
                            Stat2 = "Haste Rating"
                        });
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("InventorySlot")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jewelry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "inv_jewelry_ring_59",
                            InventorySlot = "Ring",
                            ItemId = 42643,
                            Name = "Design: Titanium Earthguard Ring"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "inv_jewelry_ring_63",
                            InventorySlot = "Ring",
                            ItemId = 42644,
                            Name = "Design: Titanium Spellshock Ring"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "inv_jewelry_ring_57",
                            InventorySlot = "Ring",
                            ItemId = 43582,
                            Name = "Design: Titanium Frostguard Ring"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "inv_jewelry_ring_55",
                            InventorySlot = "Ring",
                            ItemId = 42642,
                            Name = "Design: Titanium Impact Band"
                        },
                        new
                        {
                            Id = 5,
                            IconName = "inv_jewelry_necklace_14",
                            InventorySlot = "Neck",
                            ItemId = 42645,
                            Name = "Design: Titanium Impact Choker"
                        },
                        new
                        {
                            Id = 6,
                            IconName = "inv_jewelry_necklace_35",
                            InventorySlot = "Neck",
                            ItemId = 42647,
                            Name = "Design: Titanium Spellshock Necklace"
                        },
                        new
                        {
                            Id = 7,
                            IconName = "inv_jewelry_necklace_33",
                            InventorySlot = "Neck",
                            ItemId = 42646,
                            Name = "Design: Titanium Earthguard Chain"
                        });
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.UserDesign", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("DesignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DesignId");

                    b.HasIndex("DesignId");

                    b.ToTable("UserDesigns");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.GemCut", "GemCut")
                        .WithMany()
                        .HasForeignKey("GemCutId");

                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.Jewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId");

                    b.Navigation("GemCut");

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.UserDesign", b =>
                {
                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.Design", "Design")
                        .WithMany("UserDesigns")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.BuzzUser", "User")
                        .WithMany("UserDesigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.BuzzUser", b =>
                {
                    b.Navigation("UserDesigns");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.Navigation("UserDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
