// <auto-generated />
using System;
using Buzz.Jewelcrafting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buzz.Jewelcrafting.Migrations
{
    [DbContext(typeof(BuzzDbContext))]
    [Migration("20220929203935_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.BuzzUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("GemCutId")
                        .HasColumnType("integer");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("JewelryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GemCutId");

                    b.HasIndex("JewelryId");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.GemCut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Stat1")
                        .HasColumnType("text");

                    b.Property<string>("Stat2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GemCuts");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<string>("InventorySlot")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jewelry");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.UserDesign", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("DesignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DesignId");

                    b.HasIndex("DesignId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserDesigns");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.GemCut", "GemCut")
                        .WithMany()
                        .HasForeignKey("GemCutId");

                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.Jewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId");

                    b.Navigation("GemCut");

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.UserDesign", b =>
                {
                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.Design", "Design")
                        .WithMany("UserDesigns")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buzz.Jewelcrafting.Data.Entities.BuzzUser", "User")
                        .WithMany("UserDesigns")
                        .HasForeignKey("UserId1");

                    b.Navigation("Design");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.BuzzUser", b =>
                {
                    b.Navigation("UserDesigns");
                });

            modelBuilder.Entity("Buzz.Jewelcrafting.Data.Entities.Design", b =>
                {
                    b.Navigation("UserDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
